# Generated by Django 5.0.1 on 2024-01-24 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_items_brand_items_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='Items.company'),
        ),
    ]
