# Generated by Django 5.0.1 on 2024-01-24 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_alter_items_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='brand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='Items.company'),
        ),
    ]
